### ISSUE TITLE
Add option for random fees

### ISSUE THREAD

**Issue by KirillLykov** [godmodegalactus/mango_bencher#12]
it would be nice to have an option for random fees like in bench-tps: https://github.com/solana-labs/solana/blob/master/bench-tps/src/cli.rs#LL69C25-L69C25

**Comment by godmodegalactus** [comment]
https://github.com/godmodegalactus/mango_bencher/pull/19

**Comment by KirillLykov** [comment]
I don't recall, was it rolled back?
