### ISSUE TITLE
Migrate git submodules to crate

### ISSUE THREAD

**Issue by KirillLykov** [godmodegalactus/mango_bencher#4]
Currently, the project uses both git submodules and cargo crates. This approach makes crates dependencies resolution to be more complicated. The proposal is to move submodules to Cargo.toml (one can specify github link and commit, if he/she needs a specific version)

**Comment by godmodegalactus** [comment]
good idea

**Comment by KirillLykov** [comment]
For the reference, I use this branch in CI to avoid submodules https://github.com/godmodegalactus/mango_bencher/compare/master...KirillLykov:mango_bencher:no_solana_submod
