### ISSUE TITLE
Optimize pk_from_str_like calls (take 11% of total time)

### ISSUE THREAD

**Issue by KirillLykov** [godmodegalactus/mango_bencher#6]
From the profiler, `create_ask_bid_transaction` taxes 21% of time. Half of this is due to `pk_from_str_like`. I think it is a low-hanging fruit to get publickeys once for vector of PerpMarketCache.
Other observations:
* `serde_json::from_str` takes 6% of total time
* 16% of time is spent in futex_wait not related to send_transactions

**Comment by godmodegalactus** [comment]
Yes good idea :) thanks for profiling.
